- README.md
- src/components/leaderboards/Leaderboard/__tests__/Leaderboard-test.js
- src/components/leaderboards/Leaderboard/index.js
- src/components/leaderboards/LeaderboardItem/__tests__/LeaderboardItem-test.js
- src/components/leaderboards/TeamLeaderboardItem/index.js
- src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
- src/components/totals/FundsRaised/index.js
- src/components/totals/Goal/__tests__/Goal-test.js
- src/components/totals/Goal/index.js
- src/components/totals/TotalCharities/__tests__/TotalCharities-test.js
- src/components/totals/TotalCharities/index.js
- src/components/totals/TotalDistance/__tests__/TotalDistance-test.js
- src/components/totals/TotalDistance/index.js
- src/components/totals/TotalHeroes/__tests__/TotalHeroes-test.js
- src/components/totals/TotalHeroes/index.js
- src/components/totals/TotalHours/__tests__/TotalHours-test.js
- src/components/totals/TotalHours/index.js
Made minor changes to each component that displays a total as a number. The formatting is now exposed as a prop so you can pass in a valid [numeral.js](http://numeraljs.com/) string to format the number in different ways easily.
Also updated tests and README.
> Expose number formatting as optional prop

- README.md
- src/components/totals/Goal/__tests__/Goal-test.js
- src/components/totals/Goal/index.js
These changes make the Goal component a little more generic. By default it still renders the goal as a dollar value, but now it can be used to display other types of goals: e.g. distance goal, hours goal, etc.
It also exposes the icon class name through renderIcon prop so the default can be overridden.
> Se make goal generic

- src/components/address/AddressLookup/index.js
- src/components/forms/Input/style.scss
AddressLookup now requires minimum 5 chars for GB and 7 for elsewhere before looking up a postcode/address.  The debounce rate has been increased from 100ms to 250ms as well.
> Update address lookup rate and styling

- src/lib/getJSONP.js
Because 60 secs is an eternity
> Reduce jsonp default timeout to 20 secs

- src/components/charities/PromoCharities/__tests__/PromoCharities-test.js
- src/components/charities/PromoCharities/index.js
This makes sure that the PromotedCharities component renders charities in the order that they are passed in via the tabs prop.
Somewhat of a work-around given the charities API endpoint currently seems to return charities objects in random order.
> Ensure correct ordering of returned charities

- package.json
- src/components/address/AddressLookup/__tests__/AddressLookup-test.js
- src/components/address/AddressLookup/index.js
Not sure why this was working and now it's not, but it should require 5 chars, not 7.
Have added widget address lookup tests to ensure this doesn't happen again.
> Fix uk min postcode chars

- src/components/totals/GoalProgress/style.scss
Just fixing some minor style issues:
The goal progress was height was off by a few pixels, example: 
I set to just be 100% so it's always right (rather than static px value):
If the fundraising goal was exceeded the bar was travelling outside the component container, also the trophy icon was being hidden beneath. Example:
Fixed:
> Fix style bugs.

- src/components/totals/GoalProgress/index.js
- src/components/totals/GoalProgress/style.scss
Fixed a couple more bugs:
The trophy icon was being squashed in Firefox and IE:
Fixed:
$0.00 was displaying like this in Chrome:
Caused by 0% width on table cells being ignored. Hacky fix, but I set it to 0.001% to force correct display:
> Fix browser compatibility issues.

- README.md
- src/components/search/CharitySearchModal/__tests__/CharitySearchModal-test.js
- src/components/search/CharitySearchModal/index.js
- src/index.html
https://edhdev.atlassian.net/browse/TA-5345
- Charity Search Modal now lets you visit the charity profile page.
- Uses 'url' property in charity search response.
- Supporter needs to be updated to return new charity profile app url for Ireland charities.
> PR [TA-5345] Add Charity Search visit action

- README.md
- src/components/leaderboards/Leaderboard/__tests__/Leaderboard-test.js
- src/components/leaderboards/Leaderboard/index.js
- src/components/leaderboards/Leaderboard/style.scss
- src/components/leaderboards/LeaderboardItem/index.js
- src/components/leaderboards/LeaderboardItem/style.scss
- src/components/leaderboards/LeaderboardPaging/__tests__/LeaderboardPaging-test.js
- src/components/leaderboards/LeaderboardPaging/index.js
- src/components/leaderboards/LeaderboardPaging/style.scss
- src/components/leaderboards/LeaderboardPagingButton/__tests__/LeaderboardPagingButton-test.js
- src/components/leaderboards/LeaderboardPagingButton/index.js
- src/components/leaderboards/LeaderboardPagingButton/style.scss
- src/components/leaderboards/TeamLeaderboard/__tests__/TeamLeaderboard-test.js
- src/components/leaderboards/TeamLeaderboard/index.js
- src/components/leaderboards/TeamLeaderboard/style.scss
- src/components/leaderboards/TeamLeaderboardItem/index.js
- src/components/leaderboards/TeamLeaderboardItem/style.scss
- src/components/mixins/Leaderboard.js
- src/index.html
- src/widgets.js
- src/widgets.scss
- Switched to using JS to determine sub-component width rather than relying on pure media queries. (using DOMInfo mixin).
- Split Leaderboard component in to two separate components (Leaderboard and TeamLeaderboard). This is to deal with an issue with JS resize event listener, related to above.
- Most shared logic for leaderboards is now pushed in to a leaderboard mixin.
- The paging buttons have been spruced up and split out in to a new component LeaderboardPaging.
- The default team leaderboard render markup has been changed to the same as individual leaderboards, but the original style is still available by setting a prop `altTemplate` to `true`.
- Simple fade transition added between pages.
> Se update leaderboard

- src/components/search/SearchModal/style.scss
- src/components/search/SearchResults/style.scss
Scrolling is broken is the search modals. To see:
1. Go to: https://shared-scripts.s3.amazonaws.com/widgets-0.2.3.html
2. Type "an" to see some results.
3. With a short browser window try scrolling through results.
To fix I just moved the `overflow-y: scroll;` down a level.
> Fix overflow scrolling issue.

- src/components/forms/Input/style.scss
- src/components/sharing/ShareButton/index.js
Moved the click listener to `document` as having it on `window` was causing some weird issue with the tooltip/share box closing immediately after opening.
Also made some minor changes to to the Input component to fix the below bugs found in IE9 and 10.
> Move click listener to document. Fix visual bugs with inputs in ie.

- src/lib/__tests__/format-test.js
- src/lib/format.js
eg `format('{count:0,0} supporters', {count: 1234567})` returns `1,234,567 supporters`.
- Can now provide optional numeral format for numeric placeholders.
- Anything after the optional `:` is a format string for [numeraljs](http://numeraljs.com/).
- Currently only works for numeric values but can be extended for string params.
- This is very useful in i18n text and saves having to preformat numeric values before string interpolation.
- Fixes issue with i18n pluralisation when providing `count` param to select correct string but wanting to format the `count` param.
> Add numeral formatting to string format

- src/lib/__tests__/parseUrl-test.js
- src/lib/parseUrl.js
- I've added tests for future fixes
- Ben found a bug in parseUrl before that was fixed separately.  
- I updated result so path is '/' instead of `undefined` for simple urls like 'http://blah.com'
> Add parseUrl tests

- package.json
- src/components/forms/SearchInput/__tests__/SearchInput-test.js
- src/components/forms/SearchInput/index.js
We now clear the search input value on submit to ensure it remains blank after visiting a result and browsing back in IE10/11.
> Fix IE10/11 search input label issue 

- README.md
- src/api/__tests__/totals-test.js
- src/api/routes.js
- src/api/totals.js
- src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
- src/components/totals/FundsRaised/index.js
- src/components/totals/TotalDonations/__tests__/TotalDonations-test.js
- src/components/totals/TotalDonations/index.js
- Add workaround to _totals.js_ to request multiple campaign/page/charity totals using one call. This fixes some extremely sketchy behaviour seen in making multiple calls to the totals endpoint in quick succession.
- Updated _totals.js_ to handle logic behind making an api call when handed a single id (string) or multiple ids (array).
- Add options to _FundsRaised_ component to accept multiple charity and page ids as parameters.
> Update totals widgets

- src/components/totals/GoalProgress/style.scss
This solves the following bug found in IE9:
> Add 100% width to bar to fix IE visual bug.

- src/components/forms/Input/__tests__/Input-test.js
- src/components/forms/Input/index.js
- src/components/forms/Input/style.scss
Adds a `Input--hasIcon` class to the component root element whenever a icon is rendered. This allows for adding padding and fixing this:
So it looks like this:
> Se update inputs

- src/api/__tests__/pages-test.js
- src/api/pages.js
- src/components/fundraisers/RecentFundraisers/__tests__/RecentFundraisers-test.js
- src/components/fundraisers/RecentFundraisers/index.js
- src/components/teams/Teams/index.js
- src/docs.md
- Added a method to handle pulling page results when passed multiple campaign uids
- Updated some props that were set to be strings by default, now set to type `number`. If the user still supplies a string it won't break, just gives a console warning.
- Updated docs.
> Make fundraisers and teams components support multiple campaign uids.

- package.json
- src/components/address/AddressLookup/__tests__/AddressLookup-test.js
- src/components/address/AddressLookup/index.js
https://edhdev.atlassian.net/browse/TA-6683
- Depends entirely on initial country given to widget
- Goes straight to custom/manual entry and hides reset button as well
- Was too much hassle to enable/disable when user changes country selection
> [TA-6683] Disable address lookup for Ireland

- src/components/leaderboards/LeaderboardItem/__tests__/LeaderboardItem-test.js
- src/components/leaderboards/LeaderboardItem/index.js
- src/components/leaderboards/LeaderboardItem/style.scss
Makes the whole leaderboard item clickable (rather than just the small profile image).
> Make individual leaderboard items link to supporter pages

- src/components/leaderboards/Leaderboard/index.js
- src/components/leaderboards/LeaderboardItem/__tests__/LeaderboardItem-test.js
- src/components/leaderboards/LeaderboardItem/index.js
- src/components/leaderboards/LeaderboardItem/style.scss
- src/components/leaderboards/TeamLeaderboard/index.js
- src/docs.md
Adds a `renderImage` option to both team and individual leaderboards. Setting to false will stop the supporter page profile image from rendering. Here's what it looks like with no image:
> Add imageless option

- src/components/events/Event/index.js
Many production campaigns do not have a url specified, so this warning is incorrect.
> Fixes warning on missing campaginUrl

- src/components/charities/PromoCharities/index.js
The Promoted Charities widget was returning an error if you handed it a charity id that didn't exist in our API - This caused the widget to fall over and show infinite loading. 
It was being caused by this janky sort method that was creating a new key inside the `charities` array and passing undefined content down to children. Now it just fails gracefully by omitting the rogue id and rendering the rest.
Hooray lodash.
> Fix charity widget

- src/api/__tests__/pages-test.js
- src/api/routes.js
Page search  in routes was looking for the wrong param name and thus setting a `pageType` in search widgets was doing nothing.
> Fix search: page types

- package.json
This seems to be the source of compilation problems in a project where I am referencing edh-widgets.
> move reactify to main dependencies

- README.md
- gulpfile.js
- package.json
Added [watchify](https://github.com/substack/watchify) to reduce build time when running a watch script. Also simplified by renaming the `watch-dev` script (now `watch` does the same thing) since 100% of the time if you are running watch you don't want to waste build time on minification.
Without watchify:
With watchify:
> Add watchify, remove watch-dev script in favour of watch.

- src/api/frolCharities.js
- src/components/helpers/Overlay/index.js
- src/components/search/CharitySearchModalCustom/__tests__/CharitySearchModal-test.js
- src/components/search/CharitySearchModalCustom/index.js
- src/index.html
- src/widgets.js
Add Custom search widget to allow searching of alternate API's – to support search of fundraiseOnline charities.
Don't look to hard, this is a copy of the existing search component with a few changes.
> Add Custom search widget

- src/api/routes.js
- src/components/search/AggregateSearchModal/__tests__/AggregateSearchModal-test.js
- src/components/search/AggregateSearchModal/index.js
- src/components/search/AggregateSearchResult/__tests__/AggregateSearchResult-test.js
- src/components/search/AggregateSearchResult/index.js
- src/components/search/AggregateSearchResult/style.scss
- src/components/search/AggregateSearchResultCampaign/index.js
- src/components/search/AggregateSearchResultCharity/index.js
- src/components/search/AggregateSearchResultPage/index.js
- src/docs.md
Added the ability to constrain aggregate search component so it returns results of a specific type – basically making it "non-aggregate-y", but meaning we can replace the other search widgets with just this one.
The primary use case atm is that we need a campaign search in NFP and thought it better to do this than create yet another search widget.
Also passed the custom `onSelect` callback down to the "result" components so you can now override the default onClick behaviour. `onSelect` was already there but the prop wasn't being handed down to children.
Oh and tests, a couple of them exist now :smiley:
> [TA-7343] Expose new aggregate search options

- src/components/search/AggregateSearchModal/__tests__/AggregateSearchModal-test.js
- src/components/search/AggregateSearchModal/index.js
- src/components/search/AggregateSearchModal/style.scss
- src/components/search/AggregateSearchResult/__tests__/AggregateSearchResult-test.js
- src/components/search/AggregateSearchResult/index.js
- src/components/search/AggregateSearchResultCampaign/index.js
- src/components/search/AggregateSearchResultCampaign/style.scss
- src/components/search/AggregateSearchResultCharity/index.js
- src/components/search/AggregateSearchResultPage/index.js
- src/docs.md
Resolved some items after QA feedback:
- If a `searchType` has been defined then the filter buttons no longer trigger an onClick.
- Along with the above the hover effects for filter buttons are disabled.
- Documented the `'minimumScore` property. We needed to tweak this slightly in our implementation.
- Improved the style for campaign results that have no start date associated with them, prime example is BAU (everydayhero) result. Before it rendered as an empty square which just looked broken.
- Fixed a bunch of little lint warnings. Where do I collect my boy-scout badge? :smile:
> [TA-7343] Improve aggregate search

- package.json
- src/api/__tests__/campaigns-test.js
- src/api/routes.js
- src/components/search/AggregateSearchModal/index.js
- src/docs.md
In NFP we have something called  `beneficiaryId`.  In order to filter campaign results by "charity" in our application we need to pass the `beneficiaryId` as a parameter instead of a regular `charityUid`.
It happens that NFP's `beneficiaryId`  === `charityUuid` in supporter.
> [TA-8423] Add uuids param

- bin/update_docs
GitHub users with 2FA enabled cannot run a deploy because the docs repo clone is done through https, which isn't supported with 2FA.
Switched `DOCS_REPO` to the ssh address instead to rectify.
> GitHub 2FA support on deploy

- src/api/campaigns.js
- src/api/routes.js
- src/components/mixins/Leaderboard.js
A bit of background on this code, to explain why it's "evil-code".
We need to be able to filter leaderboards by group values, but we need this in a pretty short timeframe. In future, the solution would be to update the endpoint so that group value/s may be specified for static leaderboards, but currently, dynamic leaderboards are the only type to support group values (this is something I hope to get fixed really soon).
This code will check if there's a group value being used, and use the dynamic leaderboard accordingly.
> Leaderboard with group value to use dynamic leaderbaord endpoint

- src/components/mixins/Leaderboard.js
Individual Leaderboard components have been broken since v1.7.0. The problem was caused by `groupValues` sometimes being set as an empty array and other times being `undefined`.
This handles both cases.
> Handle empty arrays aswell as other falsey values

- package.json
Relates to the discussion over here: https://github.com/everydayhero/react-widgets/pull/387
> Set eslint version to avoid issues with 2.3.x

- package.json
Every version after 2.2.x appears to be broken for now. Let's revisit this dependency once they have fixed issues with `fb-estraverse`
> Set strict version number

- src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
I did a smart and forgot to remove an unused variable. This doesn't matter much in testing, but will cause an attempt to deploy to fail.
> Remove unused variable

- gulpfile.js
The version of cssnano used normalises the z-index values (which might sometimes be nice), it does however change the z-index of the search overlay from 1000 to 3 (which then doesn't appear in edh portal)
While a nice idea it feels fragile when included amongst lots of other sites etc
More info here https://github.com/ben-eb/gulp-cssnano/issues/8
> Preserve z-index when minifying

- src/components/supporters/Supporters/index.js
- src/docs.md
`SupporterCard` relies on `owner_footprint` data, which is only returned from the API with `type` as `individual`.
> Remove type property from Supporters widget

- src/components/search/CharitySearchModal/index.js
- src/components/search/PageSearchModal/__tests__/PageSearchModal-test.js
- src/components/search/PageSearchModal/index.js
- src/components/search/SearchResult/__tests__/SearchResult-test.js
- src/components/search/SearchResult/index.js
- src/docs.md
This makes the API (and behaviour) for charity and page search widgets a little more consistent.
On `master` currently the charity search widget appears to not prevent the default action when a custom `onSelect` function is applied. So, you could never see your custom action since the browser will immediately follow the url given to a search result anchor tag. This fixes that.
Also added the `resizeCallback` to the page search modal for consistency sake – though I do feel it is a bit poorly named.
> Make search widgets properties more consistent

- bin/deploy
- gulp_tasks/transpile.js
**Problem**
Install RW via NPM and the directory had no JS in it, just all the SCSS files. It looked like it was doing the actual transpiling (gulp build-transpile) as a dependency of the main task (gulp transpile), which then used gulp-clean to wipe out the directory after the files were transpiled.
**Solution**
Moved gulp clean into it's own task and run that first to clean out the directory before then transpiling the files, assuming that was the purpose?
Tested and works locally, with the dist folder now having all the files, transpiled and ready to go.
> Move clean into own task

- src/components/leaderboards/Leaderboard/__tests__/Leaderboard-test.js
- src/components/leaderboards/Leaderboard/index.js
- src/components/leaderboards/TeamLeaderboard/__tests__/TeamLeaderboard-test.js
- src/components/leaderboards/TeamLeaderboard/index.js
- src/components/mixins/Leaderboard.js
- src/docs.md
The everydayhero public API returns a currency symbol which can be used for a default on leaderboards. This removes the need to rely on a default translation.
> Improve symbol handling

- src/components/callstoaction/CallToActionButton/__tests__/CallToActionButton-test.js
- src/components/callstoaction/CallToActionButton/index.js
This will allow consumers of the `CallToActionButton` component to use both the `href` and `onClick` props together.
Useful in the case where you want the button to behave as a link but still execute some JavaScript.
> Allow href and onClick props to be used together

- package.json
- src/components/events/Goals/index.js
- src/components/leaderboards/Leaderboard/index.js
- src/components/leaderboards/TeamLeaderboard/index.js
- src/components/sharing/ShareButton/index.js
- src/scss/_version.scss
This resolves a breaking issue experienced on a client site where anchor tags had default transition styles applied, e.g.
```
.classname a {
transition: text-decoration 200ms ease;
}
```
This prevented `Leaderboard` & `TeamLeaderboard` paging from working consistently.
Also silences some warnings.
> Fix ReactCSSTransitionGroup errors

- src/components/search/PageSearchModal/index.js
- src/components/search/PageSearchResult/index.js
- src/components/search/SearchModal/index.js
- src/components/search/SearchResults/index.js
We needed the ability to hide the supporter's full name as this was causing privacy issues with pages in school based programs like Jump Rope. In these campaigns, the page is created by the parent, and the page is the child's first name and last initial e.g. "Child N". With the widget however, it is showing the user's full name which means the child's full name could be figured out e.g. it shows "Child N - Parent Name".
The `PageSearchResult` component is implemented internally in multiple nested components, so it wasn't as simple as passing a simple prop in and setting it. I had to add a `resultComponentProps` that gets passed down and eventually spread onto the final `resultComponent`. In our case we are forwarding on a `showSupporterName` prop, which when set to false, hides the full …
> Ability to hide or show supporter name on search result

- package.json
- src/components/events/Event/index.js
- src/components/events/UpcomingEvents/index.js
- src/scss/_version.scss
In the supporter homepage if no date is defined for the campaign 1 jan of 1970 appears.
This will hide the square leaving only the name of the campaign and the action button.
> Hide date square when no start date exists

- src/components/callstoaction/CallToActionBox/index.js
- src/components/callstoaction/CallToActionButton/index.js
- src/components/charities/PromoCharities/index.js
- src/components/events/CountDown/index.js
- src/components/events/Event/index.js
- src/components/footprint/FootprintTile/index.js
- src/components/fundraisers/FundraiserImage/index.js
- src/components/leaderboards/FitnessLeaderboardItem/index.js
- src/components/leaderboards/LeaderboardItem/index.js
- src/components/leaderboards/TeamLeaderboardItem/index.js
- src/components/search/SearchResult/index.js
- src/components/supporters/SupporterCard/index.js
- src/components/teams/Team/index.js
If any of the widgets with links off to an external page are included in an iframe, by default they would open in the same iframe window, which is rarely desired. This increases support (there was already some with a few widgets) for including widgets in iframes, and it is now the default behaviour for all external links to open in the top window.
> Iframe target fix
