src/components/charities/PromoCharitiesTabs/index.js

Fixes a pesky react warning thats been hanging around in the console for a while.

Add unique key prop to content and tab components.

---

package.json

This is an actual dependency, not just a dev dependency.

move to package dependency

---

README.md
src/components/totals/TotalDistance/__tests__/TotalDistance-test.js
src/components/totals/TotalDistance/index.js
src/components/totals/TotalHours/index.js

Fixed a ridiculous mistake in calculating kms from meters.
Also updated both TotalDistance and TotalHours components to now include all activities in the displayed total - previously it was only displaying `run` data.

Se generic mmf components

---

package.json
src/components/amount/Amount/__tests__/Amount-tests.js
src/components/amount/Amount/index.js

Also includes version bump because holy shit this is annoying to dev with.

Add hidden input element to Amount component to simplify form integration

---

src/components/address/AddressBreakdown/index.js
src/components/address/AddressLookup/index.js

AddressLookup now only auto-focuses after selecting address from list

Add AddressBreakdown autoFocus property

---

README.md
src/components/address/AddressBreakdown/index.js
src/components/address/AddressLookup/index.js
src/components/address/AddressLookup/style.scss
src/components/forms/Input/index.js

Add reset button to AddressLookup widget

---

package.json
src/components/footprint/Footprint/__tests__/Footprint-test.js
src/components/footprint/Footprint/index.js
src/components/footprint/Footprint/style.scss
src/components/footprint/FootprintGroup/index.js
src/components/footprint/FootprintGroup/style.scss
src/components/footprint/FootprintSector/index.js
src/components/footprint/FootprintSector/style.scss
src/components/footprint/FootprintTile/index.js
src/components/footprint/FootprintTile/style.scss
src/components/footprint/FootprintTip/index.js
src/components/footprint/FootprintTip/style.scss
src/components/footprint/FootprintTipLine/index.js
src/components/footprint/FootprintTipLine/style.scss
src/index.html
src/test/helpers/requestAnimationFrame.js
src/widgets.js
src/widgets.scss

Add Footprint widget

---

src/components/address/AddressLookup/index.js

On timeout, jsonp calls the given callback with null. This was not being checked properly.
Also, it wasn't cancelling address search when input below min char length.

Fix address lookup error

---

src/components/forms/Select/index.js

Fixed:
> line 77  col 13  'val' is already defined.
> line 84  col 6   Unnecessary semicolon.

Fix minor js issues raised by linter.

---

README.md
src/components/charities/PromoCharities/index.js
src/components/charities/PromoCharitiesResult/__tests__/PromoCharitiesResult-test.js
src/components/charities/PromoCharitiesResult/index.js
src/components/charities/PromoCharitiesResult/style.scss
src/components/charities/PromoCharitiesResults/index.js
src/components/charities/PromoCharitiesTabs/index.js

Add a call to action button to PromoCharities component tiles

---

src/components/address/CountrySelect/countries.js
src/components/forms/Select/index.js
src/components/forms/SelectOption/index.js
src/components/forms/SelectOption/style.scss
src/components/forms/SelectOptions/index.js

Reverts everydayhero/react-widgets#150

Revert "Fix key select and scroll into view issues"

---

src/components/forms/Select/index.js
src/components/forms/SelectOption/index.js
src/components/forms/SelectOption/style.scss
src/components/forms/SelectOptions/index.js
src/components/search/SearchInput/style.scss

- Currently selected item should be selected in list, not first
- Up/Down arrows should scroll selected item in list into view
- Tab away should not clear the selected item
- Click away should not clear the selected item
- Mouse over should not interfere with key selected item
- Filtering list should select first item by default
- Should be able to clear the selected item

Fix various forms select issues

---

package.json
src/api/campaigns.js
src/api/routes.js
src/components/events/Event/index.js
src/components/events/Event/style.scss
src/components/events/UpcomingEvents/__tests__/UpcomingEvents-test.js
src/components/events/UpcomingEvents/index.js
src/components/events/UpcomingEvents/style.scss
src/index.html
src/lib/effect.js
src/widgets.js
src/widgets.scss

Doesn't yet include blur or the heroix button code.

[TA-4816] Upcoming Events widget

---

README.md
src/components/totals/GoalProgress/__tests__/GoalProgress-test.js
src/components/totals/GoalProgress/index.js
src/components/totals/GoalProgress/style.scss
src/index.html
src/widgets.js
src/widgets.scss

goal progress bar

---

README.md
src/components/events/Event/index.js
src/components/events/Event/style.scss
src/components/events/UpcomingEvents/__tests__/UpcomingEvents-test.js
src/components/events/UpcomingEvents/index.js
src/components/events/UpcomingEvents/style.scss
src/components/mixins/DOMInfo.js
src/scss/modules/_layout.scss

https://edhdev.atlassian.net/browse/TA-4816
- Fix null event background image error
- Fix error handling of campaign loading timeout 
- Fix empty message shown instead of loading icon on window resize
- Add more tests
- Flatten Event BEM styles
- Update styles for Charity Profile

PR [TA-4816] Update upcoming events

---

src/components/address/AddressLookup/index.js
src/components/forms/Select/index.js
src/components/forms/SelectOptions/index.js

Was not triggering address change or calling output function on
clearing country which interfered with address validation in Supporter.

Fix clearing country field in AddressLookup

---

package.json
src/components/mixins/I18n.js
src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/components/totals/GoalProgress/__tests__/GoalProgress-test.js
src/components/totals/GoalProgress/index.js
src/components/totals/GoalProgress/style.scss
src/index.html
src/widgets.js

Refactor GoalProgress widget to allow use with charities

---

package.json
src/components/search/PageSearchModal/__tests__/PageSearchModal-test.js
src/components/search/PageSearchResult/__tests__/PageSearchResult-test.js
src/components/search/PageSearchResult/index.js
src/components/search/PageSearchResult/style.scss

Add supporter account name to search result to make it easier to find a supporter page

---

README.md

Widget name had been changed. Also changed the example uid to be generic.

Fix docs since refactoring.

---

src/components/footprint/Footprint/index.js

Fixes issues caused by apostrophes and other characters in IDs.

Fix invalid ids in footprint sectors

---

src/api/__tests__/campaigns-test.js
src/api/campaigns.js
src/api/routes.js
src/components/events/UpcomingEvents/__tests__/UpcomingEvents-test.js
src/components/events/UpcomingEvents/index.js

- Exposes status and sort_by and exclude_bau/pages/charities
- Updated UpcomingEvents to not get pages or charity data

Add options to campaigns api

---

src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/components/totals/GoalProgress/__tests__/GoalProgress-test.js
src/components/totals/GoalProgress/index.js

- Was showing NaN text when no goal given
- Now shows just raised amount when goal is not given (or 0) and no longer requires fallbackToFundsRaised property to be set

Fix EntityGoalProgress when no goal amount given

---

src/components/events/UpcomingEvents/__tests__/UpcomingEvents-test.js
src/components/events/UpcomingEvents/index.js

Also show the display start date, not finish date

Sort upcoming events by display start date

---

src/components/address/AddressLookup/style.scss

Update Powered by Google alignment

---

src/api/campaigns.js
src/components/callstoaction/Button/__tests__/Button-test.js
src/components/callstoaction/Button/index.js
src/components/callstoaction/Button/style.scss
src/components/events/Event/index.js
src/components/events/Event/style.scss
src/components/events/UpcomingEvents/__tests__/UpcomingEvents-test.js
src/components/events/UpcomingEvents/index.js
src/components/events/UpcomingEvents/style.scss
src/components/footprint/Footprint/__tests__/Footprint-test.js
src/components/footprint/Footprint/style.scss
src/components/footprint/FootprintTile/index.js
src/components/footprint/FootprintTile/style.scss
src/components/supporters/SupporterCard/index.js
src/components/supporters/SupporterCard/style.scss
src/components/supporters/SupporterCardGiveNow/__tests__/SupporterCardGiveNow-test.js
src/components/supporters/SupporterCardGiveNow/index.js
src/components/supporters/SupporterCardGiveNow/style.scss
src/components/supporters/Supporters/__tests__/Supporters-test.js
src/components/supporters/Supporters/index.js
src/components/supporters/Supporters/style.scss
src/widgets.scss

Whole bunch of changes to accommodate the charity profile app launch requirements.

Tweak events and supporters for charity profile app

---

README.md
package.json
src/components/events/CountDown/__tests__/CountDown-test.js
src/components/events/CountDown/index.js
src/components/events/CountDown/style.scss
src/index.html
src/lib/__tests__/i18n-test.js
src/lib/i18n.js

Component now accepts an event/campaign date and calculates how many days remaining until the event, or how many days ago it was.

Update CountDown component

---

README.md
src/api/routes.js
src/api/totals.js
src/components/totals/TotalDonations/__tests__/TotalDonations-test.js
src/components/totals/TotalDonations/index.js
src/components/totals/TotalDonations/style.scss
src/index.html
src/widgets.js
src/widgets.scss

Displays total number of donations made to a campaign.

Add a total donations widget

---

src/components/events/CountDown/index.js

Dumb mistake causing a react warning in console. :o

Fix mistake with countdown cta.

---

README.md
src/components/callstoaction/CallToActionBox/index.js
src/components/fundraisers/RecentFundraisers/index.js
src/components/teams/Teams/index.js
src/components/teams/Teams/style.scss
src/components/totals/FundsRaised/index.js
src/components/totals/Goal/index.js
src/components/totals/TotalCharities/index.js
src/components/totals/TotalDistance/index.js
src/components/totals/TotalHeroes/index.js
src/components/totals/TotalHours/index.js

Should never have been set by default the way they were... I believe this fixes #57

Remove default CSS values from props.

---

src/lib/parseUrl.js

Also fixed minor issue with matching bookmark part

Fix parseUrl hostname matching to include hyphens :)

---

README.md
src/components/tabs/Tab/__tests__/Tab-test.js
src/components/tabs/Tab/index.js
src/components/tabs/Tab/style.scss
src/components/tabs/TabDrawer/__tests__/TabDrawer-test.js
src/components/tabs/TabDrawer/index.js
src/components/tabs/TabDrawer/style.scss
src/components/tabs/TabPanel/__tests__/TabPanel-test.js
src/components/tabs/TabPanel/index.js
src/components/tabs/TabPanel/style.scss
src/components/tabs/Tabs/__tests__/Tabs-test.js
src/components/tabs/Tabs/index.js
src/components/tabs/Tabs/style.scss
src/index.html
src/widgets.js
src/widgets.scss

A generic tabs component with keyboard support. When possible I will do another PR to refactor the promoted charities widget to use these components.
Converts to an accordion if there's not enough room to show the tabs on one line.

Tabs component

---

src/api/totals.js
src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
src/components/totals/FundsRaised/index.js

Added support for page id for Funds Raised Widget
Added support for multiple campaign ids for Funds Raised Widget

Jl totals pageid

---

package.json
src/components/forms/Input/index.js
src/components/helpers/Overlay/__tests__/Overlay-test.js
src/components/helpers/Overlay/index.js
src/components/search/AggregateSearchModal/index.js
src/components/search/AggregateSearchModal/style.scss
src/components/search/AggregateSearchResult/index.js
src/components/search/AggregateSearchResultCampaign/index.js
src/components/search/AggregateSearchResultCampaign/style.scss
src/components/search/AggregateSearchResultCharity/index.js
src/components/search/AggregateSearchResultCharity/style.scss
src/components/search/AggregateSearchResultPage/index.js
src/components/search/AggregateSearchResultPage/style.scss
src/lib/causeGroups.js

Update aggregate search modal

---

README.md
src/api/__tests__/totals-test.js
src/api/totals.js
src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
src/components/totals/FundsRaised/index.js

Note: Also added tests for single campaign / page / charity IDs.

Added support for Charity ID (Funds Raised Widget)

---

src/components/forms/Input/style.scss
src/components/forms/SearchInput/style.scss
src/components/search/AggregateSearchModal/index.js
src/components/search/AggregateSearchModal/style.scss

- Fix clicking in search input (label was interfering with trying to position cursor in text by mouse click)
- Fix weird scroll issue that just appeared (removed superfluous position: relative)
- Made close button a clickable div as link was adding '#' to current url
- Update minimum search score as was missing important pages

More aggregate search fixes

---

src/components/forms/Input/index.js
src/components/search/AggregateSearchModal/index.js
src/components/search/AggregateSearchModal/style.scss

https://edhdev.atlassian.net/browse/TA-5795
- Make aggregate search tabs always visible
- Disable autocomplete/correct/spellcheck to free up vertical space
- Scroll to top of new results

PR [TA-5795] Update aggregate search

---

src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/docs.md
src/index.html

Update for the Goal Progress component to handle multiple campaign and charity uids. Switched over to using totals endpoint.

Multi uid goal progress

---

package.json

Going to 0.6.0 since there were some parameter changes to teams component.

Increment version.

---

src/components/charities/PromoCharities/index.js
src/components/charities/PromoCharitiesResult/index.js
src/components/charities/PromoCharitiesResults/__tests__/PromoCharitiesResults-test.js
src/components/charities/PromoCharitiesResults/index.js

Update result component to receive correct url via prop.

---

package.json
server.js
src/components/events/UpcomingEvents/index.js

Also changing the port to something that doesn't conflict with Supporter. Seriously wtf.

Hack to blacklist campaigns from upcoming events

---

gulpfile.js
package.json
src/components/address/AddressListing/style.scss
src/components/address/AddressLookup/index.js
src/components/address/AddressLookup/style.scss
src/components/address/AddressStatus/style.scss
src/components/address/CountrySelect/index.js
src/components/address/CountrySelect/style.scss
src/components/address/CountrySelectItem/style.scss
src/widgets.scss

TA 7481 UI updates to address widget

---

src/components/address/AddressLookup/index.js

Rather than at bottom of results

Move enter manually button to be always visiable

---

.eslintrc
src/components/address/AddressListing/index.js
src/components/address/AddressLookup/index.js
src/components/forms/Input/index.js

Focus:
Blur:
Search:
Clear search:
Blur cleared search:
Failed search:

Ta 7829 give option to enter manually when an address is not found

---

package.json
src/components/address/AddressLookup/index.js
src/components/address/AddressLookup/style.scss

Addresslookup more defensive

---

src/components/address/AddressLookup/index.js
src/components/search/PageSearchModal/index.js
src/components/search/SearchInput/index.js

Just a few annoying warnings complaining...

Add semi-colons to appease the linter

---

.eslintrc
package.json
src/components/leaderboards/Leaderboard/index.js
src/components/leaderboards/Leaderboard/style.scss
src/components/leaderboards/LeaderboardEmpty/__tests__/LeaderboardEmpty-test.js
src/components/leaderboards/LeaderboardEmpty/index.js
src/components/leaderboards/LeaderboardEmpty/style.scss
src/components/leaderboards/TeamLeaderboard/index.js
src/docs.md
src/widgets.scss

Leaderboard empty states

---

package.json
src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/components/totals/GoalProgress/__tests__/GoalProgress-test.js
src/components/totals/GoalProgress/index.js
src/docs.md

Pulled translations and some props up in to EntityGoalProgress (from GoalProgress) to make sure they are properly exposed.

Expose options for EntityGoalProgress

---

src/components/events/UpcomingEvents/index.js

Here's the order of events before new sorting ([eventName, charity_count]): 
```
[["Syria Crisis Appeal",1],["The Sunday Age City2Sea Presented by Westpac 2015",674],["Noosa Triathlon Multi Sport Festival 2015",583],["Canberra Times Australian Running Festival 2016",289],["Knight Frank Point to Pinnacle 2015",257],["The 2016 Sydney Morning Herald Half Marathon",840],["Brisbane Times City2South presented by Westpac 2016",567],["2015 Spring into Shape Series",671],["The 2016 Sun-Herald City2Surf presented by Westpac",839],["The Sun-Herald Summer Starter 2015",839],["The 2016 WAtoday Swan River Run presented by Westpac",415],["ACTIVE TRI 2016",676],["The Sunday Mail Suncorp Bank Bridge to Brisbane 2016",666],["Vita Foundation - Everyday Fundraising",2337],["Skydive for Charity",2071],["The …
```

Prioritise single charity events

---

package.json
src/api/__tests__/pages-test.js
src/api/__tests__/totals-test.js
src/api/pages.js
src/api/routes.js
src/api/totals.js
src/components/totals/TotalDonations/__tests__/TotalDonations-test.js
src/components/totals/TotalDonations/index.js
src/components/totals/TotalSupporters/__tests__/TotalSupporters-test.js
src/components/totals/TotalSupporters/index.js
src/docs.md
src/lib/__tests__/paramJoin-test.js
src/lib/paramJoin.js

- Added group value filters
- Removed StartAt & EndAt filters

TotalSupporters Group Values

---

package.json
src/api/__tests__/campaigns-test.js
src/api/routes.js
src/components/leaderboards/Leaderboard/index.js
src/components/mixins/Leaderboard.js
src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
src/components/totals/FundsRaised/index.js
src/docs.md

- Fixed EntityGoalProgress and FundsRaised components breaks with v1.0.0.
- Group value filter support for Leaderboard.

Group Value broken components & Leaderboard support

---

src/components/totals/FundsRaised/__tests__/FundsRaised-test.js
src/components/totals/FundsRaised/index.js

Adds the ability to filter the total funds raised by an array of `groupValues`.

Add groups filter to Funds Raised widget

---

gulpfile.js
package.json
src/api/campaigns.js
src/components/address/CountrySelect/index.js
src/components/charities/PromoCharities/index.js
src/components/events/UpcomingEvents/index.js
src/components/footprint/Footprint/index.js
src/components/leaderboards/FitnessLeaderboard/index.js
src/components/search/AggregateSearchModal/index.js
src/components/totals/TotalCalories/index.js
src/components/totals/TotalDistance/index.js
src/components/totals/TotalHours/index.js

- Fixes issues with Gulp build pipeline introduced in recent changes (see: `gulp-sass`)
- Adds Babelify for ES6 transpilation (yay, arrow functions)
Related to #379

Mo' dependencies, mo' problems

---

src/components/totals/EntityGoalProgress/__tests__/EntityGoalProgress-test.js
src/components/totals/EntityGoalProgress/index.js
src/docs.md

Adds a callback containing endpoint response data.

Add callback to EntityProgress

---

src/components/forms/SearchInput/style.scss

Fixing the search button offset as per below

Update search button offset

---

src/components/address/AddressLookup/style.scss
src/components/helpers/FlagIcon/style.scss
src/components/search/AggregateSearchModal/style.scss

(images are not showing at all currently - this will fix that)

Remove image-url as is not a thing

---

src/components/events/Goals/__tests__/Goals-test.js

Not sure how this test passed before but it seemed unhappy locally and on semaphore.

Fix goals test to check for relevant args

---

src/components/events/CountDown/__tests__/CountDown-test.js

This test was failing on master 😆

Fix test to no longer depend on static date

---

.buildkite/bin/announce
.buildkite/bin/build
.buildkite/bin/deploy
.buildkite/bin/test
.buildkite/docker-compose.yml
.buildkite/pipeline.yml
.gitignore
Dockerfile
bin/deploy
bin/update_docs
gulp_tasks/transpile.js
gulpfile.js
package.json

Getting rid of Semaphore
Now using buildkite.
Includes publishing to AWS and NPM
Publishing to AWS would normally include updating the docs, but for some reason the buildkite agents are not configured correctly and DEV_OP-team is too busy to fix it.

Buildkite react widgets

---

src/components/totals/TotalCustomMetric/__specs__/TotalCustomMetric-spec.js

Running `npm run build` locally surfaced some issues raised by the linter. This PR resolves them.
Here's the lint errors:

Fix lint issues with spec test

---

package.json

Update spelling in package.json to match branding

---

src/components/leaderboards/FitnessLeaderboard/__specs__/FitnessLeaderboard-spec.js
src/components/leaderboards/FitnessLeaderboard/index.js
src/components/totals/TotalCustomMetric/__specs__/TotalCustomMetric-spec.js
src/docs.md
test/helpers/common.js
test/helpers/testdom.js

Allows for selection of a desired combination of fitness activity totals to aggregate for Fitness Leaderboards.

Targeted fitness activity aggregation

---

src/lib/renderModal.js

React.unmountComponentAtNode is deprecated

---

src/components/leaderboards/Leaderboard/index.js
src/components/leaderboards/LeaderboardFailed/__specs__/LeaderboardFailed-spec.js
src/components/leaderboards/LeaderboardFailed/index.js
src/components/leaderboards/LeaderboardFailed/style.scss
src/components/leaderboards/TeamLeaderboard/index.js
src/components/mixins/Leaderboard.js
src/widgets.scss

Fix broken IE10 experience with a leaderboard failed state

---

src/components/campaigns/Summary/FundsRaised/index.js
src/components/campaigns/Summary/Goal/index.js
src/components/campaigns/Summary/GoalProgress/index.js
src/components/campaigns/Summary/GoalProgress/style.scss
src/components/campaigns/Summary/NumberOfDonations/index.js
src/components/campaigns/Summary/Stat/index.js
src/components/campaigns/Summary/Stat/style.scss
src/components/campaigns/Summary/TimeToGive/index.js
src/components/campaigns/Summary/__specs__/CampaignSummary-spec.js
src/components/campaigns/Summary/index.js
src/components/campaigns/Summary/style.scss
src/index.html
src/widgets.js
src/widgets.scss

Displays a summary of important campaign numbers and statistics

Add CampaignSummary widget

---

package.json
src/api/pages.js
src/api/routes/index.js
src/api/routes/pages/index.js
src/api/routes/staticLeaderboard/index.js
src/components/leaderboards/Leaderboard/__specs__/Leaderboard-spec.js
src/components/leaderboards/Leaderboard/index.js
src/components/leaderboards/LeaderboardEmpty/index.js
src/components/mixins/Leaderboard.js

Introduces a modular Axios-based routes system to align with v4 goals. Everything else is pretty stock standard.

Add Static Leaderboard

---

src/components/campaigns/Summary/__specs__/CampaignSummary-spec.js
src/components/campaigns/Summary/index.js

Fix to select the correct end date as this would properly reflect indefinite campaigns.

Fixed the value used to display days left

---

src/components/campaigns/Summary/index.js

Catering for indefinite campaigns

Using the indefinite property of the campaign

---

src/components/events/Event/index.js
src/components/events/UpcomingEvents/index.js

https://edhdev.atlassian.net/browse/TR-669
